INSERT INTO blumen2.config_setting(config_id,config_type,config_value,description,organisation_type,org_id) VALUES (1,'N','2017','Fiscal Year',:orgType,:orgId);
INSERT INTO blumen2.config_setting(config_id,config_type,config_value,description,organisation_type,org_id) VALUES (2,'N','3','Current Semester',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id) VALUES(3,'N','2017','Current Year',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id) VALUES(4,'L','FALSE','Is Remote',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(5,'N','1','Remote ID',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(6,'C','Compansol','Report Title 1',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(7,'C','Blumen Online for TRIO (BOT)','Report Title 2',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(8,'C','Copyright (1992-2020)','Report Footer',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(10,'N','1','Component',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(13,'N','3',' ',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(14,'D','9/1/2017 12:00:00 AM','Start Date',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(15,'D','8/31/2018 12:00:00 AM','End Date',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(16,'C','09/01','For Calculating Age',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(30,'N','1','GPA Scale',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(31,'N','1','State Test',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(42,'L','TRUE','Copy Active, Serverd Reported Status',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(43,'L','TRUE','Prompt to mark a student ACTIVE for the fiscal year',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(44,'L','TRUE','Prompt to mark a student SERVED for the fiscal year',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(45,'L','TRUE','Prompt to mark a student REPORTED for the fiscal year',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(46,'L','TRUE','Prompt to ADD a student to the fiscal year',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(47,'L','TRUE','Update First Date of Service',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(48,'L','TRUE','Update Date of last project service for the fiscal year',:orgType,:orgId);
INSERT INTO blumen2.config_setting (config_id,config_type,config_value,description,organisation_type,org_id)  VALUES(200,'N','60','Time Out',:orgType,:orgId);