INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (1,'N','2017','Fiscal Year');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (2,'N','3','Current Semester');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (3,'N','2017','Current Year');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (4,'L','FALSE','Is Remote');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (5,'N','1','Remote ID');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (6,'C','Compansol','Report Title 1');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (7,'C','Blumen Online for TRIO (BOT)','Report Title 2');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (8,'C','Copyright (1992-2020)','Report Footer');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (10,'N','1','Component');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (13,'N','3',' ');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (14,'D','9/1/2017 12:00:00 AM','Start Date');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (15,'D','8/31/2018 12:00:00 AM','End Date');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (16,'C','09/01','For Calculating Age');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (30,'N','1','GPA Scale');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (31,'N','1','State Test');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (42,'L','TRUE','Copy Active, Serverd Reported Status');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (43,'L','TRUE','Prompt to mark a student ACTIVE for the fiscal year');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (44,'L','TRUE','Prompt to mark a student SERVED for the fiscal year');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (45,'L','TRUE','Prompt to mark a student REPORTED for the fiscal year');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (46,'L','TRUE','Prompt to ADD a student to the fiscal year');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (47,'L','TRUE','Update First Date of Service');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (48,'L','TRUE','Update Date of last project service for the fiscal year');
INSERT INTO blumen2.config_setting(id,config_type,config_value,description)VALUES (200,'N','60','Time Out');