INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (1,'My Home',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (2,'Home',1);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (3,'Change My Password',2);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (4,'My Calendar',2);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (5,'Send Message',2);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (6,'Set My Preferences',2);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (7,'Time Clock',2);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (8,'View Messages',2);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (9,'My Favorite Tasks',1);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (10,'My Favorite Reports',1);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (11,'Student',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (12,'Home',11);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (13,'Asset/Inventory Management',12);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (14,'Send Bulk Text Messages',12);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (15,'Data Entry',11);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (16,'Contacts',11);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (17,'Lab Contacts',16);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (18,'Tutor Contacts',16);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (19,'Display Tutor Contacts Reminder',16);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (20,'Logs',11);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (21,'Text Message Log',20);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (22,'Text Message Replies',20);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (23,'Utilities',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (24,'Home',23);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (25,'Quick Edit',23);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (26,'Add To',23);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (27,'Generate Simillar',23);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (28,'Generate Schedule',23);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (29,'Copy Tutor Classes',28);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (30,'Tutor Schedule',28);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (31,'Generate Contacts',23);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (32,'Tutor Contacts',31);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (33,'Report',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (34,'APR',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (35,'Home',34);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (36,'APR Sections',34);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (37,'Clear Profiles',34);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (38,'Update Profiles',34);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (39,'Update Student Profile from Lab Contacts',38);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (40,'Counselor',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (41,'Home',40);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (42,'Reports',40);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (43,'Tutor',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (44,'Home',43);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (45,'Assign Students to Tutor Classes',44);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (46,'Tutor Classes',44);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (47,'Tutor Contacts',44);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (48,'Reports',43);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (49,'Teacher',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (50,'Home',49);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (51,'Reports',49);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (52,'Staff',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (53,'Home',52);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (54,'Reports',52);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (55,'Admin',null);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (56,'Home',55);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (57,'System Preferences',56);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (58,'Customize',55);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (59,'Activity / Services Group List',58);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (60,'Activity / Services List',58);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (61,'Custom Fields Value',58);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (62,'Grade / Standing Group List',58);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (63,'Pulldown Lists',58);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (64,'School Names',58);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (65,'System Tools',55);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (66,'Home',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (67,'Request Manager',66);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (68,'Standard',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (69,'Annual Performance Report Section 1',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (70,'Annual Performance Report Section 1-TS,EOC',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (71,'MS Word Mail Merge',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (72,'Parents Directory',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (73,'Parents Information',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (74,'Parents Listing',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (75,'School and Counselor Assessment',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (76,'Student Demographic Information',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (77,'Student Demographic Information-EOC',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (78,'Student Directory',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (79,'Student Information',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (80,'Student Quick Data View - Educational Opportunity Center',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (81,'User Messages',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (82,'User Messages-Detail Report',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (83,'Yearly and Financial Aid Information',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (84,'Yearly and Financial Aid Information-EOC',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (85,'Yearly Data Filter Listing',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (86,'Yearly Data Filter Listing (With Email)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (87,'Yearly Detail (Activities/ End of Year Status/Wallet/ APR Subject)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (88,'Yearly Financial Aid Information Only',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (89,'Yearly GPA (Start and End)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (90,'Yearly Listing (Activity)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (91,'Yearly Listing (Activity/ End Status/ Wallet/ APR Subject)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (92,'Yearly Listing (End Status)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (93,'Yearly Listing (End Status) Summary',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (94,'Yearly Listing (Wallet Type)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (95,'Yearly Participant Status (Start and End)',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (96,'Yearly Participant Status Listing',68);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (97,'Contacts',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (98,'Contact Activity Details for each Student',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (99,'Contact Assessment',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (100,'Contact Assessment with Activities',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (101,'Contact Data Filter Listing',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (102,'Contact Details for each Staff Member',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (103,'Contact Details for each Student',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (104,'Contact Details for each Student (sorted by Date)',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (105,'Contact Services Summary',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (106,'Contact Summary for each Staff Member',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (107,'Contact Summary for each Staff Member (All Contacts)',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (108,'Contact Summary for each Staff Member (All Contacts) with Count',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (109,'Contact Summary for each Student',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (110,'Contact Summary for each Student (All Contacts)',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (111,'Contact Data Filter Listing',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (112,'Contact Summary Overall',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (113,'Contact Summary Overall (All Contacts)',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (114,'Contact Summary Overall (All Contacts) with Count',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (115,'Lab Assessment',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (116,'Lab Contact Services Summary',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (117,'Lab Data Filter Listing',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (118,'Lab Detail Listing',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (119,'Lab Information',97);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (120,'Classes',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (121,'Class Roll',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (122,'Class Roll Sign-In Sheet',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (123,'Classes (Sorted by Class Period)',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (124,'Classes (Sorted by Days and Meeting Time)',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (125,'Classes (Sorted by Name)',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (126,'Student Schedule for Classes Filter Listing',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (127,'Student Schedule Information',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (128,'Student Schedule Information by Staff Type',120);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (129,'Semester',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (130,'Courses Information',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (131,'Courses Information (Individual)',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (132,'Courses Information with Email and Student ID',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (133,'Grade Report by Instructor',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (134,'Grade Report by Student',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (135,'Semester and Courses Information (Transcript)',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (136,'Semester Data Filter Listing',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (137,'Semester Information',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (138,'Semester Information (Individual)',129);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (139,'Graduated',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (140,'Graduated Current Mailing Labels',139);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (141,'Graduated Directory',139);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (142,'Graduated Information',139);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (143,'National Student Clearinghouse Data',139);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (144,'National Student Clearinghouse Listing',139);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (145,'Student Tracking Data',139);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (146,'Student Tracking Data Filter Listing',139);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (147,'Logs',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (148,'Attendance Date Detail Log',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (149,'Attendance Date Log',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (150,'Attendance Detail Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (151,'Attendance Information',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (152,'Custom Fields Information',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (153,'Custom Fields Information Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (154,'Custom Fields Information Listing by Type',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (155,'Exam Assessment',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (156,'Exam Data Filter Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (157,'Exam Detail Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (158,'Exam Information',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (159,'Notes Assessment',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (160,'Notes Data Filter Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (161,'Notes Detail Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (162,'Notes Information',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (163,'Stipend Assessment',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (164,'Stipend Data Filter Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (165,'Stipend Detail Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (166,'Stipend Information',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (167,'Text Message Assessment',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (168,'Text Message Data Filter Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (169,'Text Message Detail Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (170,'Text Message Information',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (171,'Wallet Assessment',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (172,'Wallet Data Filter Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (173,'Wallet Detail Listing',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (174,'Wallet Information',147);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (175,'Listing',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (176,'Academic Need Summary',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (177,'Activity / Services Group Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (178,'Activity / Services Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (179,'College Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (180,'Custom Field Names and Values',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (181,'Grade / Standing Group Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (182,'Grade / Standing Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (183,'Listing (Various Dates)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (184,'Listing by Advisor',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (185,'Listing by Age',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (186,'Listing by Birth Date',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (187,'Listing by Cohort Year',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (188,'Listing by Cohort Year and Grade / Standing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (189,'Listing by College',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (190,'Listing by College Type',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (191,'Listing by Counselor',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (192,'Listing by Dual Enrollment',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (193,'Listing by Eligibility',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (194,'Listing by Ethnicity',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (195,'Listing by FAFSA completion',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (196,'Listing by Gender',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (197,'Listing by Grade/ Standing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (198,'Listing by Major',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (199,'Listing by Rigorous Enrollment',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (200,'Listing by School',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (201,'Listing by School and Grade / Standing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (202,'Listing by Site Location',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (203,'Listing by Trio Programs',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (204,'Listing by Tutor',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (205,'Participant Status Summary',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (206,'Pulldown Lists',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (207,'Reason for Leaving Project Summary',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (208,'S.S.No Listing (All)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (209,'S.S.No Listing (System Generated Only)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (210,'School Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (211,'Student Data Filter Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (212,'Student Listing',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (213,'Student Listing (School and Grade / Standing)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (214,'Student Sign-in Sheet (Name/Grade/Signature)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (215,'Student Sign-in Sheet (Name/Signature)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (216,'Student Sign-in Sheet (Name/Signature/6 Columns)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (217,'Student Sign-in Sheet (Name/Signature/Blank Columns)',175);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (218,'Label',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (219,'File Folder Labels (Avery 5266, 2x15)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (220,'File Folder Labels (Avery 5266, School & Grade)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (221,'File Folder Labels (Avery 5267, 4x20)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (222,'File Folder Labels (Avery 5267, School & Grade)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (223,'Parents Mailing Labels (Send Mail Only)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (224,'Parents Mailing Labels (Smart Label for All Students)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (225,'Student Mailing Labels',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (226,'Student Mailing Labels (Happy Birthday to:)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (227,'Student Mailing Labels (To the Parents of:)',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (228,'Student Picture ID',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (229,'Student Picture ID # 2',218);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (230,'Staff',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (231,'Staff Member Information',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (232,'Staff Members Directory',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (233,'Staff Members Directory (Additional Address)',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (234,'Staff Members Listing',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (235,'Staff Members Mailing Labels (Additional Address)',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (236,'Staff Members Mailing Labels (Permanent Address)',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (237,'Staff Time Sheet Detail Report',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (238,'Staff Time Sheet Listing',230);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (239,'Graph',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (240,'Graph by College',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (241,'Graph by Counselor',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (242,'Graph by Eligibility',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (243,'Graph by Ethnicity',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (244,'Graph by Gender',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (245,'Graph by Grade / Standing',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (246,'Graph by Major',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (247,'Graph by Participant Status',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (248,'Graph by School',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (249,'Graph by Tutor',239);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (250,'Cross Tab',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (251,'College by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (252,'College Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (253,'College Type by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (254,'Counselor by Eligibility Type',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (255,'Counselor by Grade Standing',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (256,'Counselor by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (257,'Counselor Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (258,'Eligibility Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (259,'Eligibility Type by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (260,'End Status by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (261,'Ethnic Type by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (262,'Ethnicity Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (263,'Gender by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (264,'Gender Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (265,'Grade Level at End by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (266,'Grade Standing by Eligibility Type',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (267,'Grade/Standing Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (268,'Major Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (269,'Participant Status Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (270,'Participation Level by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (271,'School by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (272,'School Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (273,'Standing by Participant Status',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (274,'Tutor Summary by Fiscal Year',250);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (275,'Favorites',33);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (276,'Project Summary - Educational Opportunity Center',275);
INSERT INTO blumen2.menus (menus_id,name,parent_id) VALUES (277,'TEXT_ED',275);