INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(1, 'TS_DEMO', 'TS_DEMO');
INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(2, 'EOC_DEMO', 'EOC_DEMO');
INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(3, 'UB_DEMO', 'UB_DEMO');
INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(4, 'VUB_DEMO', 'VUB_DEMO');
INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(5, 'UBMS_DEMO', 'UBMS_DEMO');
INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(6, 'SSSDEMO_K1', 'SSSDEMO_K1');
INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(7, 'MCN_DEMO', 'MCN_DEMO');
INSERT INTO blumen2.organization_type
(id, descriptions, org_type)
VALUES(8, 'ProjectType8', 'ProjectType8');
