INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (1,1,'APR08_Gender','APR 08 - Gender');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (2,1,'APR09_14_Ethnicity_Race','APR 09 - 14 - Ethnicity /Race');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (3,1,'APR15_Eligibility','APR 15 - Eligibility');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (4,1,'APR16_AcademicNeed','APR 16 - Academic Need');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (5,1,'APR19_EntryGradeLevel','APR 19 - Entry Grade Level');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (6,1,'APR20_23_EnrollmentStatus','APR 20/23 - Enrollment Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (7,1,'APR21_CohortYear','APR 21 - Cohort Year');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (8,1,'APR22_ParticipantStatus','APR 22 - Participant Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (9,1,'APR24_AcademicStanding','APR 24 - Academic Standing');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (10,1,'APR26_CollegeGradeLevelatStart','APR 26 - College Grade Level at Start');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (11,1,'APR27_CollegeGradeLevelatEnd','APR 27 - College Grade Level at End');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (12,1,'APR29_ReasonforWithdrawal','APR 29 - Reason for Withdrawal');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (13,1,'APR30_TransferStatus','APR 30 - Transfer Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (14,1,'APR31_DegreeCompletedatInstitution','APR 31 - Degree Completed at Institution');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (15,1,'APR33_FieldofStudyDegree','APR 33 - Field of Study Degree');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (16,1,'APR34_PersistenceStatus_BeginningofNextYear','APR 34 - Persistence Status (Beginning of Next Year)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (17,1,'DeceasedorIncapacitated','Deceased or Incapacitated');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (18,1,'ActivityGroupType','Activity Group Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (19,1,'AdvancedMathCourse','Advanced Math Course');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (20,1,'AdvancedPlacementCourse','Advanced Placement Course');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (21,1,'Advisor','Advisor');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (22,1,'APRSubjectTypes','APR Subject Types');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (23,1,'AssetMake','Asset Make');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (24,1,'AssetModel','Asset Model');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (25,1,'AssetStatus','Asset Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (26,1,'AssetType','Asset Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (27,1,'AssociateDegree','Associate Degree');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (28,1,'AtRiskAlgebra','At Risk Algebra');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (29,1,'AtRiskLowGPA','At Risk Low GPA');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (30,1,'AtRiskOutofSchool','At Risk Out of School');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (31,1,'AtRiskStandardTest','At Risk Standard Test');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (32,1,'AttendedCommunityCollege','Attended Community College');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (33,1,'BachelorsDegree','Bachelors Degree');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (34,1,'BirthPlace','Birth Place');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (35,1,'BOTFormName','BOT Form Name');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (36,1,'BOTFormStatus','BOT Form Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (37,1,'Certificate_DiplomaCompleted','Certificate/ Diploma Completed');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (38,1,'CircumstancesofRecheduling','Circumstances of Recheduling');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (39,1,'City','City');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (40,1,'Codes','Codes');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (41,1,'CollegeEntranceExam','College Entrance Exam');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (42,1,'CollegeReady','College Ready');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (43,1,'CollegeType','College Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (44,1,'CompareSymbols','Compare Symbols');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (45,1,'CompletionYear','Completion Year');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (46,1,'ComponentType','Component Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (47,1,'ComponentType_APR','Component Type-APR');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (48,1,'ContactStaffType','Contact Staff Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (49,1,'ContactType','Contact Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (50,1,'CourseInstructor','Course Instructor');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (51,1,'CourseName','Course Name');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (52,1,'CourseNumber','Course Number');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (53,1,'CustomField1','Custom Field 1');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (54,1,'CustomField2','Custom Field 2');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (55,1,'CustomField3','Custom Field 3');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (56,1,'CustomField4','Custom Field 4');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (57,1,'CustomFieldNames','Custom Field Names');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (58,1,'Days','Days');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (59,1,'DisconnectedYouth','Disconnected Youth');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (60,1,'DoctorateEmploymentActivity','Doctorate Employment Activity');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (61,1,'DualEnrollment','Dual Enrollment');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (62,1,'DualEnrollmentCredentials','Dual Enrollment Credentials');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (63,1,'EligibilityType','Eligibility Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (64,1,'Employment','Employment');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (65,1,'EndStatus','End Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (66,1,'EnglishInstructions','English Instructions');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (67,1,'EthnicType_NationalOrigin','Ethnic Type (National Origin)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (68,1,'ExamName','Exam Name');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (69,1,'FAFSAcompletion','FAFSA completion');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (70,1,'FinancialAid','Financial Aid');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (71,1,'FinancialAidName','Financial Aid Name');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (72,1,'FinancialAidUn_metReason','Financial Aid Un-met Reason');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (73,1,'FinancialAidUnmetName','Financial Aid Unmet Name');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (74,1,'ForeignLanguageInstructions','Foreign Language Instructions');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (75,1,'Frequencyofcontactsbetweenparticipants','Frequency of contacts between participants');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (76,1,'FundingSource','Funding Source');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (77,1,'GPAScale','GPA Scale');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (78,1,'GradeLevel_atendofreportingperiod','Grade Level (at end of reporting period)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (79,1,'GradeProgressionOverYear','Grade Progression Over Year');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (80,1,'GraduateAssistantships','Graduate Assistantships');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (81,1,'GraduateCurrentYearofStudy','Graduate Current Year of Study');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (82,1,'GraduateDegreeEarned','Graduate Degree Earned');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (83,1,'GraduateDegreeIn','Graduate Degree In');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (84,1,'GraduateEducationalStatus','Graduate Educational Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (85,1,'GraduateEmploymentType','Graduate Employment Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (86,1,'GraduateSchoolAdmissionsTest','Graduate School Admissions Test');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (87,1,'GraduateSchoolEnrollmentObjective','Graduate School Enrollment Objective');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (88,1,'GraduateStudentPersistenceStatus','Graduate Student Persistence Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (89,1,'GraduatingCohortYearofBachelorsDegree','Graduating Cohort Year of Bachelor Degree');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (90,1,'GraduationCohortYear','Graduation Cohort Year');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (91,1,'HealthName','Health Name');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (92,1,'HighSchoolGraduationStatus','High School Graduation Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (93,1,'ImprovedScoreonStandardizedTest','Improved Score on Standardized Test');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (94,1,'IncomeLevel','Income Level');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (95,1,'IncomeSource','Income Source');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (96,1,'Initiative','Initiative');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (97,1,'Internship','Internship');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (98,1,'LengthofProjectParticipation','Length of Project Participation');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (99,1,'LimitedEnglishProficiencyStatus','Limited English Proficiency Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (100,1,'Major','Major');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (101,1,'MaritalStatus','Marital Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (102,1,'MathematicsInstructions_Tutorials','Mathematics Instructions/ Tutorials');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (103,1,'MeetingTime','Meeting Time');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (104,1,'MessagePriorityType','Message Priority Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (105,1,'MilitaryRank','Military Rank');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (106,1,'MilitaryType','Military Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (107,1,'OldEndStatus_ForTSandEOC_priorto2006_07','Old End Status-For TS and EOC (prior to 2006-07)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (108,1,'Parent_GuardianRelationship','Parent/ Guardian Relationship');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (109,1,'ParticipantRetentioninProject','Participant Retention in Project');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (110,1,'ParticipantStatus_atendofReportingPeriod','Participant Status (at end of Reporting Period)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (111,1,'ParticipationLevel','Participation Level');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (112,1,'PersistenceGraduationStatusatendofyear','Persistence Graduation Status at end of year');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (113,1,'PhoneType','Phone Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (114,1,'PostsecondaryCompletionObjective','Postsecondary Completion Objective');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (115,1,'PostsecondaryEnrollmentObjective','Postsecondary Enrollment Objective');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (116,1,'PostsecondaryGradingPeriod','Postsecondary Grading Period');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (117,1,'PostsecondaryPersistenceObjective_Denominator','Postsecondary Persistence Objective-Denominator');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (118,1,'PostsecondaryPersistenceObjective_Numerator','Postsecondary Persistence Objective-Numerator');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (119,1,'PostsecondaryRemediation','Postsecondary Remediation');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (120,1,'PostsecondarySTEMDegree','Postsecondary STEM Degree');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (121,1,'ReasonforVisit','Reason for Visit');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (122,1,'ReasonleftGraduateSchool','Reason left Graduate School');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (123,1,'ReasonNotEnrolled','Reason Not Enrolled');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (124,1,'ReasonofRecheduling','Reason of Recheduling');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (125,1,'RecordUpdated','Record Updated');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (126,1,'Recruitment','Recruitment');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (127,1,'ReferredBy','Referred By');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (128,1,'ResearchActivities','Research Activities');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (129,1,'RevisedScheduledCompletionYear','Revised Scheduled Completion Year');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (130,1,'RigorousEnrollment','Rigorous Enrollment');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (131,1,'Room','Room');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (132,1,'ScheduledCompletionYear','Scheduled Completion Year');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (133,1,'ScholarlyActivity','Scholarly Activity');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (134,1,'ScienceInstruction_Tutorials','Science Instruction/Tutorials');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (135,1,'SecondarySchoolRetention','Secondary School Retention');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (136,1,'SemesterType','Semester Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (137,1,'SiteLocation','Site Location');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (138,1,'SourceofPostsecondaryEducationInformation','Source of Postsecondary Education Information');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (139,1,'StaffCodes','Staff Codes');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (140,1,'StaffCustomField','Staff Custom Field');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (141,1,'StandingGroupType_APRColumn','Standing Group Type (APR Column)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (142,1,'State_PostalAddress','State (Postal Address)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (143,1,'StateGradelevelinwhichstudentwasAssessed','State Grade level in which student was Assessed');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (144,1,'StateMet10thGradeAchievementStandardOptions','State Met 10th Grade Achievement Standard Options');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (145,1,'StateMet8thGradeAchievementStandardOptions','State Met 8th Grade Achievement Standard Options');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (146,1,'State_DevelopedTesttoMeasureAcademicSkills','State-Developed Test to Measure Academic Skills');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (147,1,'STEMMajor','STEM Major');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (148,1,'Subject_Classes_Contacts','Subject ( Classes/ Contacts)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (149,1,'SummerBridge','Summer Bridge');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (150,1,'TrackingCompleted','Tracking Completed');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (151,1,'TrackingGraduate','Tracking Graduate');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (152,1,'TrioPrograms','Trio Programs');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (153,1,'TypeofStandarizedTests','Type of Standarized Tests');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (154,1,'UB_UBMS_VUBSummerresidentialProgramType','"UB,UBMS,VUB Summer residential Program Type"');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (155,1,'UBMSProjecttype','UBMS Project type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (156,1,'VeteranCalltoActiveDutyLength','Veteran Call to Active Duty Length');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (157,1,'VeteranCalledtoActiveDutyStatus','Veteran Called to Active Duty Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (158,1,'VeteranEducationalStatus_atend','Veteran Educational Status (at end)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (159,1,'VeteranEducationalStatus_EntryintoProject','Veteran Educational Status (Entry into Project)');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (160,1,'VeteranEmploymentStatus','Veteran Employment Status');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (161,1,'VeteranFinancialAid','Veteran Financial Aid');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (162,1,'WalletName','Wallet Name');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (163,1,'WalletType','Wallet Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (164,1,'YearlyChildServiceHeading','Yearly Child Service Heading');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (165,1,'YearlyChildServiceType','Yearly Child Service Type');
INSERT INTO blumen2.pulldown (id,active,code,name)VALUES (166,1,'Yes_NoOptions','Yes-No Options');
