INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR08_Gender','APR 08 - Gender',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR09_14_Ethnicity_Race','APR 09 - 14 - Ethnicity /Race',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR15_Eligibility','APR 15 - Eligibility',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR16_AcademicNeed','APR 16 - Academic Need',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR19_EntryGradeLevel','APR 19 - Entry Grade Level',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR20_23_EnrollmentStatus','APR 20/23 - Enrollment Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR21_CohortYear','APR 21 - Cohort Year',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR22_ParticipantStatus','APR 22 - Participant Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR24_AcademicStanding','APR 24 - Academic Standing',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR26_CollegeGradeLevelatStart','APR 26 - College Grade Level at Start',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR27_CollegeGradeLevelatEnd','APR 27 - College Grade Level at End',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR29_ReasonforWithdrawal','APR 29 - Reason for Withdrawal',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR30_TransferStatus','APR 30 - Transfer Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR31_DegreeCompletedatInstitution','APR 31 - Degree Completed at Institution',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR33_FieldofStudyDegree','APR 33 - Field of Study Degree',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APR34_PersistenceStatus_BeginningofNextYear','APR 34 - Persistence Status (Beginning of Next Year)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'DeceasedorIncapacitated','Deceased or Incapacitated',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ActivityGroupType','Activity Group Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AdvancedMathCourse','Advanced Math Course',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AdvancedPlacementCourse','Advanced Placement Course',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Advisor','Advisor',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'APRSubjectTypes','APR Subject Types',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES ( 1,'AssetMake','Asset Make',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AssetModel','Asset Model',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AssetStatus','Asset Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AssetType','Asset Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AssociateDegree','Associate Degree',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AtRiskAlgebra','At Risk Algebra',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AtRiskLowGPA','At Risk Low GPA',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AtRiskOutofSchool','At Risk Out of School',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AtRiskStandardTest','At Risk Standard Test',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'AttendedCommunityCollege','Attended Community College',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'BachelorsDegree','Bachelors Degree',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'BirthPlace','Birth Place',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'BOTFormName','BOT Form Name',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'BOTFormStatus','BOT Form Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Certificate_DiplomaCompleted','Certificate/ Diploma Completed',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CircumstancesofRecheduling','Circumstances of Recheduling',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'City','City',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Codes','Codes',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CollegeEntranceExam','College Entrance Exam',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CollegeReady','College Ready',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CollegeType','College Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CompareSymbols','Compare Symbols',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CompletionYear','Completion Year',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ComponentType','Component Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ComponentType_APR','Component Type-APR',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ContactStaffType','Contact Staff Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ContactType','Contact Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CourseInstructor','Course Instructor',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CourseName','Course Name',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CourseNumber','Course Number',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CustomField1','Custom Field 1',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CustomField2','Custom Field 2',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CustomField3','Custom Field 3',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CustomField4','Custom Field 4',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'CustomFieldNames','Custom Field Names',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Days','Days',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'DisconnectedYouth','Disconnected Youth',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'DoctorateEmploymentActivity','Doctorate Employment Activity',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'DualEnrollment','Dual Enrollment',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'DualEnrollmentCredentials','Dual Enrollment Credentials',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'EligibilityType','Eligibility Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Employment','Employment',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'EndStatus','End Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'EnglishInstructions','English Instructions',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'EthnicType_NationalOrigin','Ethnic Type (National Origin)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ExamName','Exam Name',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'FAFSAcompletion','FAFSA completion',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'FinancialAid','Financial Aid',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'FinancialAidName','Financial Aid Name',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'FinancialAidUn_metReason','Financial Aid Un-met Reason',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'FinancialAidUnmetName','Financial Aid Unmet Name',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ForeignLanguageInstructions','Foreign Language Instructions',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Frequencyofcontactsbetweenparticipants','Frequency of contacts between participants',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'FundingSource','Funding Source',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GPAScale','GPA Scale',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GradeLevel_atendofreportingperiod','Grade Level (at end of reporting period)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GradeProgressionOverYear','Grade Progression Over Year',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateAssistantships','Graduate Assistantships',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateCurrentYearofStudy','Graduate Current Year of Study',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateDegreeEarned','Graduate Degree Earned',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateDegreeIn','Graduate Degree In',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateEducationalStatus','Graduate Educational Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateEmploymentType','Graduate Employment Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateSchoolAdmissionsTest','Graduate School Admissions Test',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateSchoolEnrollmentObjective','Graduate School Enrollment Objective',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduateStudentPersistenceStatus','Graduate Student Persistence Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduatingCohortYearofBachelorsDegree','Graduating Cohort Year of Bachelor Degree',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'GraduationCohortYear','Graduation Cohort Year',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'HealthName','Health Name',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'HighSchoolGraduationStatus','High School Graduation Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ImprovedScoreonStandardizedTest','Improved Score on Standardized Test',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'IncomeLevel','Income Level',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'IncomeSource','Income Source',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Initiative','Initiative',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Internship','Internship',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'LengthofProjectParticipation','Length of Project Participation',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'LimitedEnglishProficiencyStatus','Limited English Proficiency Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Major','Major',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'MaritalStatus','Marital Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'MathematicsInstructions_Tutorials','Mathematics Instructions/ Tutorials',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'MeetingTime','Meeting Time',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'MessagePriorityType','Message Priority Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'MilitaryRank','Military Rank',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'MilitaryType','Military Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'OldEndStatus_ForTSandEOC_priorto2006_07','Old End Status-For TS and EOC (prior to 2006-07)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Parent_GuardianRelationship','Parent/ Guardian Relationship',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ParticipantRetentioninProject','Participant Retention in Project',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ParticipantStatus_atendofReportingPeriod','Participant Status (at end of Reporting Period)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ParticipationLevel','Participation Level',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PersistenceGraduationStatusatendofyear','Persistence Graduation Status at end of year',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PhoneType','Phone Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PostsecondaryCompletionObjective','Postsecondary Completion Objective',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PostsecondaryEnrollmentObjective','Postsecondary Enrollment Objective',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PostsecondaryGradingPeriod','Postsecondary Grading Period',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PostsecondaryPersistenceObjective_Denominator','Postsecondary Persistence Objective-Denominator',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PostsecondaryPersistenceObjective_Numerator','Postsecondary Persistence Objective-Numerator',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PostsecondaryRemediation','Postsecondary Remediation',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'PostsecondarySTEMDegree','Postsecondary STEM Degree',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ReasonforVisit','Reason for Visit',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ReasonleftGraduateSchool','Reason left Graduate School',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ReasonNotEnrolled','Reason Not Enrolled',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ReasonofRecheduling','Reason of Recheduling',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'RecordUpdated','Record Updated',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Recruitment','Recruitment',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ReferredBy','Referred By',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ResearchActivities','Research Activities',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'RevisedScheduledCompletionYear','Revised Scheduled Completion Year',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'RigorousEnrollment','Rigorous Enrollment',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Room','Room',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ScheduledCompletionYear','Scheduled Completion Year',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ScholarlyActivity','Scholarly Activity',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'ScienceInstruction_Tutorials','Science Instruction/Tutorials',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'SecondarySchoolRetention','Secondary School Retention',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'SemesterType','Semester Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'SiteLocation','Site Location',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'SourceofPostsecondaryEducationInformation','Source of Postsecondary Education Information',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'StaffCodes','Staff Codes',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'StaffCustomField','Staff Custom Field',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'StandingGroupType_APRColumn','Standing Group Type (APR Column)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'State_PostalAddress','State (Postal Address)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'StateGradelevelinwhichstudentwasAssessed','State Grade level in which student was Assessed',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'StateMet10thGradeAchievementStandardOptions','State Met 10th Grade Achievement Standard Options',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'StateMet8thGradeAchievementStandardOptions','State Met 8th Grade Achievement Standard Options',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'State_DevelopedTesttoMeasureAcademicSkills','State-Developed Test to Measure Academic Skills',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'STEMMajor','STEM Major',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Subject_Classes_Contacts','Subject ( Classes/ Contacts)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'SummerBridge','Summer Bridge',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'TrackingCompleted','Tracking Completed',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'TrackingGraduate','Tracking Graduate',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'TrioPrograms','Trio Programs',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'TypeofStandarizedTests','Type of Standarized Tests',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'UB_UBMS_VUBSummerresidentialProgramType','"UB,UBMS,VUB Summer residential Program Type"',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'UBMSProjecttype','UBMS Project type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'VeteranCalltoActiveDutyLength','Veteran Call to Active Duty Length',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'VeteranCalledtoActiveDutyStatus','Veteran Called to Active Duty Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'VeteranEducationalStatus_atend','Veteran Educational Status (at end)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'VeteranEducationalStatus_EntryintoProject','Veteran Educational Status (Entry into Project)',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'VeteranEmploymentStatus','Veteran Employment Status',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'VeteranFinancialAid','Veteran Financial Aid',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'WalletName','Wallet Name',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'WalletType','Wallet Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'YearlyChildServiceHeading','Yearly Child Service Heading',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'YearlyChildServiceType','Yearly Child Service Type',:orgId);
INSERT INTO blumen2.pulldown (active,code,name,org_id) VALUES (1,'Yes_NoOptions','Yes-No Options',:orgId);
