insert into blumen2.security_question_list(name,org_id,question_type) values('What is your date of birth', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values('Which city were you born in', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'What make was your first car', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'What is your favorite sports team?', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'SQ 1-1', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'SQ 1-2', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'SQ 1-3', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'SQ 1-4', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'SQ 1-5', :orgId,1);
insert into blumen2.security_question_list(name,org_id,question_type) values( 'what is your fav food?',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('which city you were born in ?',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('What is your pet''s name?',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('favorite nfl team',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('SQ 2-1',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('SQ 2-2',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('SQ 2-3',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('SQ 2-4',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('SQ 2-5',:orgId,2);
insert into blumen2.security_question_list(name,org_id,question_type) values('SQ 2-6',:orgId,2);