insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values('What is your pet''s name', ?,?,?);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(2,'What is your date of birth', 'EOC_DEMO' ,1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(3,'Which city were you born in', 'EOC_DEMO' ,1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(4, 'What make was your first car', 'EOC_DEMO',1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(5, 'What is your favorite sports team?', 'EOC_DEMO',1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(6, 'SQ 1-1', 'EOC_DEMO',1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(7,'SQ 1-2', 'EOC_DEMO' ,1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(8, 'SQ 1-3', 'EOC_DEMO',1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(9, 'SQ 1-4', 'EOC_DEMO',1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(10, 'SQ 1-5', 'EOC_DEMO',1,1);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(11,'what is your fav food?','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(12,'which city you were born in ?','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(13,'What is your pet's name?','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(14,'favorite nfl team','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(15,'SQ 2-1','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(16,'SQ 2-2','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(17,'SQ 2-3','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(18,'SQ 2-4','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(19,'SQ 2-5','EOC_DEMO',1 ,2);
insert into blumen2.security_question_list(id,name,org_code,org_id,question_type) values(20,'SQ 2-6','EOC_DEMO',1 ,2);
