insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All',:org_id,'Y',null,1,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Allow Easy Add to Pulldown List',:org_id,'Y',0,2,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add New Student',:org_id,'Y',0,3,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Student',:org_id,'Y',0,4,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Show System Serial Number',:org_id,'Y',null,5,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Summary',:org_id,'Y',0,6,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Interactive Summary',:org_id,'Y',0,7,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Manage Filter List',:org_id,'Y',0,8,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Student Data',:org_id,'Y',0,9,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk E-mails',:org_id,'Y',8,10,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk Text Messaging',:org_id,'Y',8,11,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Postsecondary Tracking',:org_id,'Y',8,12,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Filter',:org_id,'Y',8,13,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Entry',:org_id,'Y',12,14,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Parent / Guardian Data Entry',:org_id,'Y',13,15,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Filter',:org_id,'Y',12,16,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Entry',:org_id,'Y',15,17,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Filter',:org_id,'Y',12,18,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Entry',:org_id,'Y',17,19,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Filter',:org_id,'Y',12,20,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Entry',:org_id,'Y',19,21,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Courses Data Entry',:org_id,'Y',20,22,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Filter',:org_id,'Y',12,23,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Entry',:org_id,'Y',22,24,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tracking Data Entry',:org_id,'Y',12,25,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Personalized Letters',:org_id,'Y',12,26,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Demograhic Data',:org_id,'Y',22,27,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Filter',:org_id,'Y',12,28,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Data Entry',:org_id,'Y',27,29,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check Out',:org_id,'Y',28,30,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check In',:org_id,'Y',28,31,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Logs',:org_id,'Y',0,32,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Filter',:org_id,'Y',31,33,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Entry',:org_id,'Y',32,34,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Filter',:org_id,'Y',31,35,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Entry',:org_id,'Y',34,36,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Filter',:org_id,'Y',31,37,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Data Entry',:org_id,'Y',36,38,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Filter',:org_id,'Y',31,39,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Entry',:org_id,'Y',38,40,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Filter',:org_id,'Y',31,41,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Entry',:org_id,'Y',40,42,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Log',:org_id,'Y',31,43,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'Y',42,44,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Contacts',:org_id,'Y',0,45,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Filter',:org_id,'Y',44,46,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Data',:org_id,'Y',45,47,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Filter',:org_id,'Y',44,48,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Data',:org_id,'Y',47,49,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Filter',:org_id,'Y',44,50,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Data',:org_id,'Y',49,51,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Filter',:org_id,'Y',44,52,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Data',:org_id,'Y',51,53,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Filter',:org_id,'Y',44,54,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Data',:org_id,'Y',53,55,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Display Reminders',:org_id,'Y',44,56,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Classes',:org_id,'Y',0,57,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Filter',:org_id,'Y',56,58,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Data',:org_id,'Y',57,59,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Filter',:org_id,'Y',56,60,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Data',:org_id,'Y',59,61,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Filter',:org_id,'Y',56,62,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Data',:org_id,'Y',61,63,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Filter',:org_id,'Y',56,64,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Data',:org_id,'Y',63,65,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Schedules',:org_id,'Y',0,66,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Filter',:org_id,'Y',65,67,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Data',:org_id,'Y',66,68,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Counselor Classes',:org_id,'Y',67,69,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Filter',:org_id,'Y',65,70,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Data',:org_id,'Y',69,71,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Tutor Classes',:org_id,'Y',70,72,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Filter',:org_id,'Y',65,73,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Data',:org_id,'Y',72,74,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Teacher Classes',:org_id,'Y',73,75,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Filter',:org_id,'Y',65,76,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Data',:org_id,'Y',75,77,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Staff Classes',:org_id,'Y',76,78,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Staff',:org_id,'Y',0,79,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'Y',78,80,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'Y',78,81,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Data Filter/ Entry',:org_id,'Y',78,82,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Data Filter/ Entry',:org_id,'Y',78,83,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Reports (Request Manager)',:org_id,'Y',0,84,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Annual Performance Report',:org_id,'Y',83,85,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All APR Sections',:org_id,'Y',84,86,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1-Part II',:org_id,'Y',85,87,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section I',:org_id,'Y',85,88,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1- Part 4',:org_id,'Y',85,89,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II',:org_id,'Y',85,90,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II (Quick Edit)',:org_id,'Y',85,91,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 4-Part E',:org_id,'Y',85,92,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section III',:org_id,'Y',85,93,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section IV',:org_id,'Y',85,94,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments',:org_id,'Y',85,95,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments Data Entry',:org_id,'Y',85,96,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Provision of Services',:org_id,'Y',85,97,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('APR Objectives / PE Points',:org_id,'Y',85,98,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy APR Data',:org_id,'Y',85,99,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update fields from Tracking Data',:org_id,'Y',85,100,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update All Profiles',:org_id,'Y',84,101,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Counselor Contacts',:org_id,'Y',100,102,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Tutor Contacts',:org_id,'Y',100,103,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Teacher Contacts',:org_id,'Y',100,104,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Staff Contacts',:org_id,'Y',100,105,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Lab Contacts',:org_id,'Y',100,106,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Wallet',:org_id,'Y',100,107,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Utilities',:org_id,'Y',0,108,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Change S.S.No.',:org_id,'Y',107,109,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Change',:org_id,'Y',107,110,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('National Student Clearinghouse Data Interface',:org_id,'Y',107,111,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Quick Edit',:org_id,'Y',107,112,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Demographic Information',:org_id,'Y',111,113,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Yearly and Financial Aid Inform',:org_id,'Y',111,114,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Semester Information',:org_id,'Y',111,115,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Courses Information',:org_id,'Y',111,116,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Add Students to',:org_id,'Y',107,117,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Fiscal Year',:org_id,'Y',116,118,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Semester',:org_id,'Y',116,119,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Graduated List',:org_id,'Y',116,120,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Similar',:org_id,'Y',107,121,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Attendance Log',:org_id,'Y',120,122,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Exam',:org_id,'Y',120,123,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Wallet',:org_id,'Y',120,124,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Stipend',:org_id,'Y',120,125,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly APR Subjects',:org_id,'Y',120,126,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'Y',120,127,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'Y',120,128,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,129,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'Y',120,130,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'Y',120,131,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,132,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Custom Field Values',:org_id,'Y',120,133,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Notes Log',:org_id,'Y',120,134,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Lab Logs',:org_id,'Y',120,135,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Contacts',:org_id,'Y',107,136,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'Y',135,137,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'Y',135,138,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Contacts',:org_id,'Y',135,139,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Contacts',:org_id,'Y',135,140,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Schedule',:org_id,'Y',107,141,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Schedule',:org_id,'Y',140,142,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Tutor Schedule',:org_id,'Y',140,143,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Schedule',:org_id,'Y',140,144,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Schedule',:org_id,'Y',140,145,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Counselor Classes',:org_id,'Y',140,146,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Staff Classes',:org_id,'Y',140,147,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Teacher Classes',:org_id,'Y',140,148,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Tutor Classes',:org_id,'Y',140,149,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Administration',:org_id,'Y',0,150,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Set System Preferences',:org_id,'Y',149,151,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Config Settings',:org_id,'Y',149,152,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('E-Mail Setup',:org_id,'Y',149,153,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Roles',:org_id,'Y',149,154,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('User Names and Password',:org_id,'Y',149,155,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Customize',:org_id,'Y',149,156,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services Group List',:org_id,'Y',155,157,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services List',:org_id,'Y',155,158,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('College Names',:org_id,'Y',155,159,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Custom Fields Values',:org_id,'Y',155,160,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing Group List',:org_id,'Y',155,161,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing List',:org_id,'Y',155,162,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Pulldown Lists',:org_id,'Y',155,163,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('School Names',:org_id,'Y',155,164,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('System Tools',:org_id,'Y',149,165,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Time Clock Manager',:org_id,'Y',164,166,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Students',:org_id,'Y',164,167,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Recall Students',:org_id,'Y',164,168,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update GPA Wizard',:org_id,'Y',164,169,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Year',:org_id,'Y',164,170,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Age',:org_id,'Y',164,171,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Management',:org_id,'Y',149,172,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Detail',:org_id,'Y',171,173,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'Y',172,174,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete All',:org_id,'Y',0,175,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Mobile App Access',:org_id,'Y',0,176,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Trio Blumen Lab',:org_id,'Y',0,177,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Setting Preferences',:org_id,'Y',176,178,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Group checkout button',:org_id,'Y',177,179,'ADM');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('ImportWizard',:org_id,'Y',0,180,'ADM');