insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All',:org_id,'Y',null,1, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Allow Easy Add to Pulldown List',:org_id,'Y',0,2, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add New Student',:org_id,'Y',0,3, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Student',:org_id,'N',0,4, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Show System Serial Number',:org_id,'N',null,5, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Summary',:org_id,'Y',0,6, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Interactive Summary',:org_id,'Y',0,7, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Manage Filter List',:org_id,'Y',0,8, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Student Data',:org_id,'Y',0,9, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk E-mails',:org_id,'Y',8,10, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk Text Messaging',:org_id,'Y',8,11, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Postsecondary Tracking',:org_id,'Y',8,12, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Filter',:org_id,'Y',8,13, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Entry',:org_id,'Y',12,14, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Parent / Guardian Data Entry',:org_id,'Y',13,15, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Filter',:org_id,'Y',12,16, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Entry',:org_id,'Y',15,17, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Filter',:org_id,'Y',12,18, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Entry',:org_id,'Y',17,19, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Filter',:org_id,'Y',12,20, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Entry',:org_id,'Y',19,21, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Courses Data Entry',:org_id,'Y',20,22, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Filter',:org_id,'Y',12,23, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Entry',:org_id,'Y',22,24, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tracking Data Entry',:org_id,'Y',12,25, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Personalized Letters',:org_id,'Y',12,26, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Demograhic Data',:org_id,'Y',22,27, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Filter',:org_id,'Y',12,28, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Data Entry',:org_id,'Y',27,29, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check Out',:org_id,'Y',28,30, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check In',:org_id,'Y',28,31, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Logs',:org_id,'Y',0,32, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Filter',:org_id,'Y',31,33, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Entry',:org_id,'Y',32,34, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Filter',:org_id,'Y',31,35, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Entry',:org_id,'Y',34,36, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Filter',:org_id,'Y',31,37, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Data Entry',:org_id,'Y',36,38, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Filter',:org_id,'Y',31,39, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Entry',:org_id,'Y',38,40, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Filter',:org_id,'Y',31,41, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Entry',:org_id,'Y',40,42, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Log',:org_id,'R',31,43, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'R',42,44, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Contacts',:org_id,'Y',0,45, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Filter',:org_id,'N',44,46, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Data',:org_id,'N',45,47, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Filter',:org_id,'N',44,48, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Data',:org_id,'N',47,49, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Filter',:org_id,'N',44,50, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Data',:org_id,'N',49,51, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Filter',:org_id,'Y',44,52, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Data',:org_id,'Y',51,53, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Filter',:org_id,'Y',44,54, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Data',:org_id,'Y',53,55, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Display Reminders',:org_id,'Y',44,56, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Classes',:org_id,'Y',0,57, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Filter',:org_id,'N',56,58, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Data',:org_id,'N',57,59, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Filter',:org_id,'Y',56,60, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Data',:org_id,'Y',59,61, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Filter',:org_id,'N',56,62, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Data',:org_id,'N',61,63, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Filter',:org_id,'Y',56,64, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Data',:org_id,'Y',63,65, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Schedules',:org_id,'Y',0,66, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Filter',:org_id,'N',65,67, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Data',:org_id,'N',66,68, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Counselor Classes',:org_id,'N',67,69, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Filter',:org_id,'N',65,70, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Data',:org_id,'N',69,71, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Tutor Classes',:org_id,'N',70,72, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Filter',:org_id,'N',65,73, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Data',:org_id,'N',72,74, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Teacher Classes',:org_id,'N',73,75, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Filter',:org_id,'Y',65,76, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Data',:org_id,'Y',75,77, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Staff Classes',:org_id,'Y',76,78, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Staff',:org_id,'Y',0,79, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'N',78,80, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'N',78,81, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Data Filter/ Entry',:org_id,'Y',78,82, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Data Filter/ Entry',:org_id,'Y',78,83, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Reports (Request Manager)',:org_id,'Y',0,84, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Annual Performance Report',:org_id,'Y',83,85, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All APR Sections',:org_id,'Y',84,86, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1-Part II',:org_id,'Y',85,87, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section I',:org_id,'Y',85,88, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1- Part 4',:org_id,'Y',85,89, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II',:org_id,'Y',85,90, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II (Quick Edit)',:org_id,'Y',85,91, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 4-Part E',:org_id,'Y',85,92, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section III',:org_id,'Y',85,93, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section IV',:org_id,'Y',85,94, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments',:org_id,'Y',85,95, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments Data Entry',:org_id,'Y',85,96, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Provision of Services',:org_id,'Y',85,97, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('APR Objectives / PE Points',:org_id,'Y',85,98, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy APR Data',:org_id,'Y',85,99, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update fields from Tracking Data',:org_id,'Y',85,100, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update All Profiles',:org_id,'N',84,101, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Counselor Contacts',:org_id,'N',100,102, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Tutor Contacts',:org_id,'N',100,103, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Teacher Contacts',:org_id,'N',100,104, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Staff Contacts',:org_id,'N',100,105, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Lab Contacts',:org_id,'Y',100,106, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Wallet',:org_id,'N',100,107, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Utilities',:org_id,'Y',0,108, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Change S.S.No.',:org_id,'N',107,109, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Change',:org_id,'Y',107,110, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('National Student Clearinghouse Data Interface',:org_id,'Y',107,111, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Quick Edit',:org_id,'Y',107,112, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Demographic Information',:org_id,'Y',111,113, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Yearly and Financial Aid Inform',:org_id,'Y',111,114, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Semester Information',:org_id,'Y',111,115, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Courses Information',:org_id,'Y',111,116, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Add Students to',:org_id,'N',107,117, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Fiscal Year',:org_id,'N',116,118, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Semester',:org_id,'N',116,119, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Graduated List',:org_id,'N',116,120, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Similar',:org_id,'Y',107,121, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Attendance Log',:org_id,'Y',120,122, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Exam',:org_id,'Y',120,123, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Wallet',:org_id,'Y',120,124, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Stipend',:org_id,'Y',120,125, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly APR Subjects',:org_id,'Y',120,126, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'Y',120,127, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'Y',120,128, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,129, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'Y',120,130, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'Y',120,131, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,132, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Custom Field Values',:org_id,'Y',120,133, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Notes Log',:org_id,'N',120,134, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Lab Logs',:org_id,'Y',120,135, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Contacts',:org_id,'Y',107,136, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'N',135,137, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'N',135,138, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Contacts',:org_id,'Y',135,139, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Contacts',:org_id,'Y',135,140, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Schedule',:org_id,'Y',107,141, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Schedule',:org_id,'N',140,142, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Tutor Schedule',:org_id,'N',140,143, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Schedule',:org_id,'N',140,144, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Schedule',:org_id,'Y',140,145, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Counselor Classes',:org_id,'N',140,146, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Staff Classes',:org_id,'Y',140,147, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Teacher Classes',:org_id,'N',140,148, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Tutor Classes',:org_id,'N',140,149, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Administration',:org_id,'N',0,150, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Set System Preferences',:org_id,'R',149,151, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Config Settings',:org_id,'N',149,152, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('E-Mail Setup',:org_id,'N',149,153, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Roles',:org_id,'N',149,154, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('User Names and Password',:org_id,'N',149,155, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Customize',:org_id,'R',149,156, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services Group List',:org_id,'R',155,157, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services List',:org_id,'R',155,158, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('College Names',:org_id,'R',155,159, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Custom Fields Values',:org_id,'Y',155,160, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing Group List',:org_id,'R',155,161, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing List',:org_id,'R',155,162, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Pulldown Lists',:org_id,'R',155,163, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('School Names',:org_id,'R',155,164, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('System Tools',:org_id,'N',149,165, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Time Clock Manager',:org_id,'N',164,166, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Students',:org_id,'N',164,167, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Recall Students',:org_id,'N',164,168, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update GPA Wizard',:org_id,'N',164,169, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Year',:org_id,'N',164,170, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Age',:org_id,'N',164,171, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Management',:org_id,'N',149,172, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Detail',:org_id,'N',171,173, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'N',172,174, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete All',:org_id,'N',0,175, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Mobile App Access',:org_id,'Y',0,176, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Trio Blumen Lab',:org_id,'Y',0,177, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Setting Preferences',:org_id,'R',176,178, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Group checkout button',:org_id,'Y',177,179, 'STA');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('ImportWizard',:org_id,'N',0,180, 'STA');