insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All',:org_id,'Y',null,1,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Allow Easy Add to Pulldown List',:org_id,'Y',0,2,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add New Student',:org_id,'Y',0,3,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Student',:org_id,'N',0,4,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Show System Serial Number',:org_id,'N',null,5,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Summary',:org_id,'Y',0,6,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Interactive Summary',:org_id,'Y',0,7,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Manage Filter List',:org_id,'Y',0,8,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Student Data',:org_id,'N',0,9,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk E-mails',:org_id,'N',8,10,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk Text Messaging',:org_id,'Y',8,11,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Postsecondary Tracking',:org_id,'Y',8,12,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Filter',:org_id,'N',8,13,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Entry',:org_id,'N',12,14,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Parent / Guardian Data Entry',:org_id,'N',13,15,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Filter',:org_id,'Y',12,16,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Entry',:org_id,'Y',15,17,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Filter',:org_id,'N',12,18,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Entry',:org_id,'N',17,19,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Filter',:org_id,'N',12,20,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Entry',:org_id,'N',19,21,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Courses Data Entry',:org_id,'N',20,22,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Filter',:org_id,'N',12,23,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Entry',:org_id,'N',22,24,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tracking Data Entry',:org_id,'N',12,25,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Personalized Letters',:org_id,'N',12,26,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Demograhic Data',:org_id,'N',22,27,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Filter',:org_id,'Y',12,28,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Data Entry',:org_id,'Y',27,29,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check Out',:org_id,'Y',28,30,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check In',:org_id,'Y',28,31,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Logs',:org_id,'N',0,32,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Filter',:org_id,'N',31,33,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Entry',:org_id,'N',32,34,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Filter',:org_id,'N',31,35,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Entry',:org_id,'N',34,36,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Filter',:org_id,'N',31,37,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Data Entry',:org_id,'N',36,38,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Filter',:org_id,'N',31,39,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Entry',:org_id,'N',38,40,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Filter',:org_id,'N',31,41,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Entry',:org_id,'N',40,42,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Log',:org_id,'N',31,43,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'N',42,44,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Contacts',:org_id,'Y',0,45,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Filter',:org_id,'N',44,46,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Data',:org_id,'N',45,47,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Filter',:org_id,'Y',44,48,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Data',:org_id,'Y',47,49,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Filter',:org_id,'N',44,50,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Data',:org_id,'N',49,51,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Filter',:org_id,'N',44,52,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Data',:org_id,'N',51,53,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Filter',:org_id,'Y',44,54,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Data',:org_id,'Y',53,55,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Display Reminders',:org_id,'Y',44,56,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Classes',:org_id,'Y',0,57,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Filter',:org_id,'N',56,58,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Data',:org_id,'N',57,59,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Filter',:org_id,'Y',56,60,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Data',:org_id,'Y',59,61,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Filter',:org_id,'N',56,62,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Data',:org_id,'N',61,63,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Filter',:org_id,'N',56,64,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Data',:org_id,'N',63,65,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Schedules',:org_id,'Y',0,66,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Filter',:org_id,'N',65,67,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Data',:org_id,'N',66,68,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Counselor Classes',:org_id,'N',67,69,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Filter',:org_id,'Y',65,70,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Data',:org_id,'Y',69,71,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Tutor Classes',:org_id,'Y',70,72,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Filter',:org_id,'N',65,73,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Data',:org_id,'N',72,74,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Teacher Classes',:org_id,'N',73,75,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Filter',:org_id,'N',65,76,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Data',:org_id,'N',75,77,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Staff Classes',:org_id,'N',76,78,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Staff',:org_id,'N',0,79,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'N',78,80,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'N',78,81,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Data Filter/ Entry',:org_id,'N',78,82,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Data Filter/ Entry',:org_id,'N',78,83,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Reports (Request Manager)',:org_id,'R',0,84,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Annual Performance Report',:org_id,'N',83,85,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All APR Sections',:org_id,'N',84,86,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1-Part II',:org_id,'N',85,87,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section I',:org_id,'N',85,88,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1- Part 4',:org_id,'Y',85,89,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II',:org_id,'N',85,90,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II (Quick Edit)',:org_id,'N',85,91,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 4-Part E',:org_id,'Y',85,92,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section III',:org_id,'N',85,93,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section IV',:org_id,'N',85,94,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments',:org_id,'N',85,95,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments Data Entry',:org_id,'N',85,96,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Provision of Services',:org_id,'N',85,97,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('APR Objectives / PE Points',:org_id,'N',85,98,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy APR Data',:org_id,'N',85,99,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update fields from Tracking Data',:org_id,'N',85,100,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update All Profiles',:org_id,'N',84,101,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Counselor Contacts',:org_id,'N',100,102,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Tutor Contacts',:org_id,'N',100,103,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Teacher Contacts',:org_id,'N',100,104,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Staff Contacts',:org_id,'N',100,105,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Lab Contacts',:org_id,'Y',100,106,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Wallet',:org_id,'N',100,107,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Utilities',:org_id,'Y',0,108,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Change S.S.No.',:org_id,'N',107,109,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Change',:org_id,'N',107,110,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('National Student Clearinghouse Data Interface',:org_id,'N',107,111,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Quick Edit',:org_id,'N',107,112,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Demographic Information',:org_id,'N',111,113,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Yearly and Financial Aid Inform',:org_id,'N',111,114,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Semester Information',:org_id,'N',111,115,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Courses Information',:org_id,'N',111,116,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Add Students to',:org_id,'N',107,117,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Fiscal Year',:org_id,'N',116,118,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Semester',:org_id,'N',116,119,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Graduated List',:org_id,'N',116,120,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Similar',:org_id,'N',107,121,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Attendance Log',:org_id,'N',120,122,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Exam',:org_id,'N',120,123,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Wallet',:org_id,'N',120,124,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Stipend',:org_id,'N',120,125,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly APR Subjects',:org_id,'N',120,126,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'N',120,127,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'N',120,128,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,129,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'N',120,130,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'N',120,131,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'N',120,132,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Custom Field Values',:org_id,'N',120,133,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Notes Log',:org_id,'N',120,134,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Lab Logs',:org_id,'Y',120,135,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Contacts',:org_id,'Y',107,136,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'N',135,137,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'Y',135,138,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Contacts',:org_id,'N',135,139,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Contacts',:org_id,'N',135,140,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Schedule',:org_id,'Y',107,141,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Schedule',:org_id,'N',140,142,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Tutor Schedule',:org_id,'Y',140,143,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Schedule',:org_id,'N',140,144,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Schedule',:org_id,'N',140,145,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Counselor Classes',:org_id,'N',140,146,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Staff Classes',:org_id,'N',140,147,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Teacher Classes',:org_id,'N',140,148,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Tutor Classes',:org_id,'Y',140,149,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Administration',:org_id,'N',0,150,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Set System Preferences',:org_id,'R',149,151,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Config Settings',:org_id,'N',149,152,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('E-Mail Setup',:org_id,'N',149,153,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Roles',:org_id,'N',149,154,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('User Names and Password',:org_id,'N',149,155,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Customize',:org_id,'R',149,156,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services Group List',:org_id,'R',155,157,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services List',:org_id,'R',155,158,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('College Names',:org_id,'R',155,159,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Custom Fields Values',:org_id,'Y',155,160,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing Group List',:org_id,'R',155,161,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing List',:org_id,'R',155,162,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Pulldown Lists',:org_id,'R',155,163,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('School Names',:org_id,'R',155,164,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('System Tools',:org_id,'N',149,165,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Time Clock Manager',:org_id,'N',164,166,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Students',:org_id,'N',164,167,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Recall Students',:org_id,'N',164,168,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update GPA Wizard',:org_id,'N',164,169,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Year',:org_id,'N',164,170,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Age',:org_id,'N',164,171,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Management',:org_id,'N',149,172,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Detail',:org_id,'N',171,173,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'N',172,174,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete All',:org_id,'N',0,175,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Mobile App Access',:org_id,'Y',0,176,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Trio Blumen Lab',:org_id,'Y',0,177,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Setting Preferences',:org_id,'N',176,178,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Group checkout button',:org_id,'Y',177,179,'TUT');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('ImportWizard',:org_id,'N',0,180,'TUT');