insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All',:org_id,'Y',null,1,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Allow Easy Add to Pulldown List',:org_id,'Y',0,2,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add New Student',:org_id,'Y',0,3,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Student',:org_id,'N',0,4,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Show System Serial Number',:org_id,'N',null,5,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Summary',:org_id,'Y',0,6,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Interactive Summary',:org_id,'Y',0,7,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Manage Filter List',:org_id,'Y',0,8,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Student Data',:org_id,'Y',0,9,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk E-mails',:org_id,'Y',8,10,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk Text Messaging',:org_id,'Y',8,11,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Postsecondary Tracking',:org_id,'Y',8,12,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Filter',:org_id,'Y',8,13,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Entry',:org_id,'Y',12,14,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Parent / Guardian Data Entry',:org_id,'Y',13,15,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Filter',:org_id,'Y',12,16,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Entry',:org_id,'Y',15,17,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Filter',:org_id,'Y',12,18,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Entry',:org_id,'Y',17,19,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Filter',:org_id,'Y',12,20,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Entry',:org_id,'Y',19,21,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Courses Data Entry',:org_id,'Y',20,22,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Filter',:org_id,'Y',12,23,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Entry',:org_id,'Y',22,24,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tracking Data Entry',:org_id,'Y',12,25,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Personalized Letters',:org_id,'Y',12,26,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Demograhic Data',:org_id,'Y',22,27,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Filter',:org_id,'Y',12,28,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Data Entry',:org_id,'Y',27,29,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check Out',:org_id,'Y',28,30,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check In',:org_id,'Y',28,31,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Logs',:org_id,'Y',0,32,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Filter',:org_id,'Y',31,33,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Entry',:org_id,'Y',32,34,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Filter',:org_id,'Y',31,35,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Entry',:org_id,'Y',34,36,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Filter',:org_id,'Y',31,37,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Data Entry',:org_id,'Y',36,38,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Filter',:org_id,'Y',31,39,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Entry',:org_id,'Y',38,40,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Filter',:org_id,'Y',31,41,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Entry',:org_id,'Y',40,42,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Log',:org_id,'Y',31,43,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'Y',42,44,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Contacts',:org_id,'Y',0,45,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Filter',:org_id,'Y',44,46,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Data',:org_id,'Y',45,47,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Filter',:org_id,'Y',44,48,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Data',:org_id,'Y',47,49,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Filter',:org_id,'Y',44,50,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Data',:org_id,'Y',49,51,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Filter',:org_id,'Y',44,52,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Data',:org_id,'Y',51,53,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Filter',:org_id,'Y',44,54,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Data',:org_id,'Y',53,55,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Display Reminders',:org_id,'Y',44,56,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Classes',:org_id,'Y',0,57,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Filter',:org_id,'Y',56,58,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Data',:org_id,'Y',57,59,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Filter',:org_id,'Y',56,60,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Data',:org_id,'Y',59,61,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Filter',:org_id,'Y',56,62,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Data',:org_id,'Y',61,63,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Filter',:org_id,'Y',56,64,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Data',:org_id,'Y',63,65,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Schedules',:org_id,'Y',0,66,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Filter',:org_id,'Y',65,67,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Data',:org_id,'Y',66,68,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Counselor Classes',:org_id,'Y',67,69,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Filter',:org_id,'Y',65,70,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Data',:org_id,'Y',69,71,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Tutor Classes',:org_id,'Y',70,72,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Filter',:org_id,'Y',65,73,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Data',:org_id,'Y',72,74,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Teacher Classes',:org_id,'Y',73,75,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Filter',:org_id,'Y',65,76,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Data',:org_id,'Y',75,77,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Staff Classes',:org_id,'Y',76,78,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Staff',:org_id,'Y',0,79,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'Y',78,80,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'Y',78,81,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Data Filter/ Entry',:org_id,'N',78,82,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Data Filter/ Entry',:org_id,'Y',78,83,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Reports (Request Manager)',:org_id,'Y',0,84,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Annual Performance Report',:org_id,'Y',83,85,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All APR Sections',:org_id,'Y',84,86,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1-Part II',:org_id,'Y',85,87,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section I',:org_id,'Y',85,88,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1- Part 4',:org_id,'Y',85,89,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II',:org_id,'Y',85,90,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II (Quick Edit)',:org_id,'Y',85,91,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 4-Part E',:org_id,'Y',85,92,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section III',:org_id,'Y',85,93,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section IV',:org_id,'Y',85,94,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments',:org_id,'Y',85,95,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments Data Entry',:org_id,'Y',85,96,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Provision of Services',:org_id,'Y',85,97,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('APR Objectives / PE Points',:org_id,'Y',85,98,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy APR Data',:org_id,'Y',85,99,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update fields from Tracking Data',:org_id,'Y',85,100,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update All Profiles',:org_id,'N',84,101,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Counselor Contacts',:org_id,'N',100,102,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Tutor Contacts',:org_id,'N',100,103,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Teacher Contacts',:org_id,'N',100,104,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Staff Contacts',:org_id,'N',100,105,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Lab Contacts',:org_id,'Y',100,106,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Wallet',:org_id,'N',100,107,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Utilities',:org_id,'Y',0,108,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Change S.S.No.',:org_id,'N',107,109,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Change',:org_id,'Y',107,110,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('National Student Clearinghouse Data Interface',:org_id,'Y',107,111,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Quick Edit',:org_id,'Y',107,112,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Demographic Information',:org_id,'Y',111,113,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Yearly and Financial Aid Inform',:org_id,'Y',111,114,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Semester Information',:org_id,'Y',111,115,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Courses Information',:org_id,'Y',111,116,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Add Students to',:org_id,'Y',107,117,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Fiscal Year',:org_id,'Y',116,118,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Semester',:org_id,'Y',116,119,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Graduated List',:org_id,'Y',116,120,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Similar',:org_id,'Y',107,121,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Attendance Log',:org_id,'Y',120,122,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Exam',:org_id,'Y',120,123,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Wallet',:org_id,'Y',120,124,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Stipend',:org_id,'Y',120,125,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly APR Subjects',:org_id,'Y',120,126,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'Y',120,127,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'Y',120,128,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,129,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'Y',120,130,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'Y',120,131,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,132,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Custom Field Values',:org_id,'Y',120,133,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Notes Log',:org_id,'Y',120,134,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Lab Logs',:org_id,'Y',120,135,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Contacts',:org_id,'Y',107,136,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'Y',135,137,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'Y',135,138,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Contacts',:org_id,'Y',135,139,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Contacts',:org_id,'Y',135,140,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Schedule',:org_id,'Y',107,141,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Schedule',:org_id,'Y',140,142,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Tutor Schedule',:org_id,'Y',140,143,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Schedule',:org_id,'Y',140,144,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Schedule',:org_id,'Y',140,145,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Counselor Classes',:org_id,'Y',140,146,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Staff Classes',:org_id,'Y',140,147,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Teacher Classes',:org_id,'Y',140,148,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Tutor Classes',:org_id,'Y',140,149,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Administration',:org_id,'Y',0,150,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Set System Preferences',:org_id,'R',149,151,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Config Settings',:org_id,'N',149,152,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('E-Mail Setup',:org_id,'N',149,153,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Roles',:org_id,'N',149,154,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('User Names and Password',:org_id,'N',149,155,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Customize',:org_id,'R',149,156,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services Group List',:org_id,'R',155,157,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services List',:org_id,'R',155,158,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('College Names',:org_id,'R',155,159,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Custom Fields Values',:org_id,'Y',155,160,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing Group List',:org_id,'R',155,161,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing List',:org_id,'R',155,162,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Pulldown Lists',:org_id,'R',155,163,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('School Names',:org_id,'R',155,164,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('System Tools',:org_id,'Y',149,165,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Time Clock Manager',:org_id,'N',164,166,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Students',:org_id,'N',164,167,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Recall Students',:org_id,'N',164,168,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update GPA Wizard',:org_id,'Y',164,169,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Year',:org_id,'Y',164,170,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Age',:org_id,'N',164,171,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Management',:org_id,'N',149,172,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Detail',:org_id,'N',171,173,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'N',172,174,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete All',:org_id,'N',0,175,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Mobile App Access',:org_id,'Y',0,176,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Trio Blumen Lab',:org_id,'Y',0,177,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Setting Preferences',:org_id,'R',176,178,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Group checkout button',:org_id,'Y',177,179,'COU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('ImportWizard',:org_id,'N',0,180,'COU');