insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All',:org_id,'R',null,1, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Allow Easy Add to Pulldown List',:org_id,'N',0,2, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add New Student',:org_id,'N',0,3, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Student',:org_id,'N',0,4, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Show System Serial Number',:org_id,'N',null,5, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Summary',:org_id,'R',0,6, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Project Interactive Summary',:org_id,'R',0,7, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Manage Filter List',:org_id,'N',0,8, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Student Data',:org_id,'R',0,9, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk E-mails',:org_id,'N',8,10, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Send Bulk Text Messaging',:org_id,'N',8,11, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Postsecondary Tracking',:org_id,'N',8,12, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Filter',:org_id,'R',8,13, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Student Data Entry',:org_id,'R',12,14, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Parent / Guardian Data Entry',:org_id,'R',13,15, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Filter',:org_id,'R',12,16, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Text Message Data Entry',:org_id,'R',15,17, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Filter',:org_id,'R',12,18, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Yearly Data Entry',:org_id,'R',17,19, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Filter',:org_id,'R',12,20, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Semester Data Entry',:org_id,'R',19,21, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Courses Data Entry',:org_id,'R',20,22, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Filter',:org_id,'R',12,23, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Graduated Data Entry',:org_id,'R',22,24, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tracking Data Entry',:org_id,'R',12,25, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Personalized Letters',:org_id,'R',12,26, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Demograhic Data',:org_id,'R',22,27, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Filter',:org_id,'R',12,28, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Data Entry',:org_id,'R',27,29, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check Out',:org_id,'R',28,30, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Asset Check In',:org_id,'R',28,31, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Logs',:org_id,'R',0,32, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Filter',:org_id,'R',31,33, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Attendance Data Entry',:org_id,'R',32,34, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Filter',:org_id,'R',31,35, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Stipend Data Entry',:org_id,'R',34,36, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Filter',:org_id,'R',31,37, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Exam Data Entry',:org_id,'R',36,38, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Filter',:org_id,'R',31,39, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Wallet Data Entry',:org_id,'R',38,40, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Filter',:org_id,'R',31,41, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Notes Data Entry',:org_id,'R',40,42, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Log',:org_id,'N',31,43, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'N',42,44, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Contacts',:org_id,'N',0,45, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Filter',:org_id,'N',44,46, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Contact Data',:org_id,'N',45,47, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Filter',:org_id,'N',44,48, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Contact Data',:org_id,'N',47,49, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Filter',:org_id,'N',44,50, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Contact Data',:org_id,'N',49,51, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Filter',:org_id,'N',44,52, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Contact Data',:org_id,'N',51,53, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Filter',:org_id,'Y',44,54, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Contact Data',:org_id,'Y',53,55, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Display Reminders',:org_id,'N',44,56, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Classes',:org_id,'R',0,57, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Filter',:org_id,'R',56,58, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Classes Data',:org_id,'R',57,59, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Filter',:org_id,'R',56,60, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Classes Data',:org_id,'R',59,61, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Filter',:org_id,'R',56,62, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Classes Data',:org_id,'R',61,63, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Filter',:org_id,'R',56,64, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Classes Data',:org_id,'R',63,65, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Schedules',:org_id,'R',0,66, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Filter',:org_id,'R',65,67, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Schedule Data',:org_id,'R',66,68, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Counselor Classes',:org_id,'R',67,69, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Filter',:org_id,'R',65,70, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Tutor Schedule Data',:org_id,'R',69,71, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Tutor Classes',:org_id,'R',70,72, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Filter',:org_id,'R',65,73, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Schedule Data',:org_id,'R',72,74, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Teacher Classes',:org_id,'R',73,75, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Filter',:org_id,'R',65,76, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Schedule Data',:org_id,'R',75,77, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Select Staff Classes',:org_id,'R',76,78, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Staff',:org_id,'N',0,79, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'N',78,80, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Counselor Data Filter/ Entry',:org_id,'N',78,81, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Teacher Data Filter/ Entry',:org_id,'N',78,82, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Data Filter/ Entry',:org_id,'N',78,83, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Reports (Request Manager)',:org_id,'R',0,84, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Annual Performance Report',:org_id,'N',83,85, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All APR Sections',:org_id,'N',84,86, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1-Part II',:org_id,'N',85,87, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section I',:org_id,'N',85,88, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 1- Part 4',:org_id,'N',85,89, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II',:org_id,'N',85,90, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section II (Quick Edit)',:org_id,'N',85,91, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report Section 4-Part E',:org_id,'N',85,92, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section III',:org_id,'N',85,93, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Annual Performance Report - Section IV',:org_id,'N',85,94, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments',:org_id,'N',85,95, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Goals / Objectives and Accomplishments Data Entry',:org_id,'N',85,96, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Provision of Services',:org_id,'N',85,97, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('APR Objectives / PE Points',:org_id,'N',85,98, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy APR Data',:org_id,'N',85,99, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update fields from Tracking Data',:org_id,'N',85,100, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update All Profiles',:org_id,'N',84,101, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Counselor Contacts',:org_id,'N',100,102, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Tutor Contacts',:org_id,'N',100,103, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Teacher Contacts',:org_id,'N',100,104, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Staff Contacts',:org_id,'N',100,105, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Lab Contacts',:org_id,'N',100,106, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Student Profile from Wallet',:org_id,'N',100,107, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Utilities',:org_id,'N',0,108, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Change S.S.No.',:org_id,'N',107,109, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Change',:org_id,'N',107,110, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('National Student Clearinghouse Data Interface',:org_id,'N',107,111, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Quick Edit',:org_id,'N',107,112, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Demographic Information',:org_id,'N',111,113, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Yearly and Financial Aid Inform',:org_id,'N',111,114, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Semester Information',:org_id,'N',111,115, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Quick Edit Student Courses Information',:org_id,'N',111,116, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Add Students to',:org_id,'N',107,117, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Fiscal Year',:org_id,'N',116,118, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Semester',:org_id,'N',116,119, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Add Students to Graduated List',:org_id,'N',116,120, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Similar',:org_id,'N',107,121, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Attendance Log',:org_id,'N',120,122, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Exam',:org_id,'N', 120,123, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Wallet',:org_id,'N',120,124, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Stipend',:org_id,'N',120,125, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly APR Subjects',:org_id,'N',120,126, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'N',120,127, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'N',120,128, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'Y',120,129, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Activity',:org_id,'N',120,130, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly End Status',:org_id,'N',120,131, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Yearly Wallet',:org_id,'N',120,132, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Custom Field Values',:org_id,'N',120,133, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Notes Log',:org_id,'N',120,134, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Lab Logs',:org_id,'N',120,135, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Contacts',:org_id,'N',107,136, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'N',135,137, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Contacts',:org_id,'N',135,138, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Contacts',:org_id,'N',135,139, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Contacts',:org_id,'N',135,140, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('All Generate Schedule',:org_id,'N',107,141, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Counselor Schedule',:org_id,'N',140,142, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Tutor Schedule',:org_id,'N',140,143, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Teacher Schedule',:org_id,'N',140,144, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Generate Similar Staff Schedule',:org_id,'N',140,145, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Counselor Classes',:org_id,'N',140,146, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Staff Classes',:org_id,'N',140,147, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Teacher Classes',:org_id,'N',140,148, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Copy Tutor Classes',:org_id,'N',140,149, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Administration',:org_id,'N',0,150, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Set System Preferences',:org_id,'N',149,151, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Config Settings',:org_id,'N',149,152, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('E-Mail Setup',:org_id,'N',149,153, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Roles',:org_id,'N',149,154, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('User Names and Password',:org_id,'N',149,155, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Customize',:org_id,'R',149,156, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services Group List',:org_id,'R',155,157, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Activity / Services List',:org_id,'R',155,158, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('College Names',:org_id,'R',155,159, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Custom Fields Values',:org_id,'Y',155,160, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing Group List',:org_id,'R',155,161, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Grade / Standing List',:org_id,'R',155,162, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Pulldown Lists',:org_id,'R',155,163, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('School Names',:org_id,'R',155,164, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('System Tools',:org_id,'N',149,165, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Staff Time Clock Manager',:org_id,'N',164,166, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete Students',:org_id,'N',164,167, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Recall Students',:org_id,'N',164,168, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update GPA Wizard',:org_id,'N',164,169, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Year',:org_id,'N',164,170, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Update Age',:org_id,'N',164,171, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Management',:org_id,'N',149,172, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Detail',:org_id,'N',171,173, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('BOT Form Submission Detail',:org_id,'N',172,174, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Delete All',:org_id,'N',0,175, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Mobile App Access',:org_id,'N',0,176, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Trio Blumen Lab',:org_id,'N',0,177, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Lab Setting Preferences',:org_id,'N',176,178, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('Group checkout button',:org_id,'N',177,179, 'STU');
insert  into blumen2.privileges ( name,org_id, access_type,parent_code, code, role_code) values ('ImportWizard',:org_id,'N',0,180, 'STU');